sudo: false
language: go

go:
- "1.13"

cache:
  directories:
  - $GOPATH/pkg/mod
  - $GOPATH/bin
  - $HOME/.cache/go-build

branches:
  only:
    - master
    - production

before_install:
- 'git config --global url.git@github.com:.insteadof https://github.com/'

script:
- make lint test

notifications:
  slack:
    secure: JTOQ25Dh3Xoh3p9hbXsC+hhMP6XmYftjZjErrweX9fcRjJ7/vOmQ9md3Kg0ekweeiEh7ALJLLTnaV8rLO0AIhjYntAEMvRWprWF/cQGBeig1CoJgkoWGPn4dKULw1ONcw3LLhUxJeL6NImEuZA4d/lMeJx28jIdtU3s5jLJKkJI=
